name: Build and test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup k3s
      uses: debianmaster/actions-k3s@master
      with:
        version: 'v1.20.8-k3s1'
    - name: Setup .NET SDK 5
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'
    - name: Install dependencies
      run: dotnet restore
    - name: Install tool dependencies
      run: dotnet tool restore
    - name: Check formatting
      run: dotnet tool run fantomas --check --recurse src
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    - name: Run BootAndSync mission
      run: dotnet run --project src/App/App.fsproj --configuration Release -- mission BootAndSync --image stellar/stellar-core:17.2.0-620.7cf753c.focal --kubeconfig $KUBECONFIG --namespace default --ingress-class traefik --ingress-internal-domain local --ingress-external-host localhost --uneven-sched
    - uses: actions/upload-artifact@v2
      with:
        name: destination
        path: destination/
        retention-days: 30
