name: Build and test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup k3d
      uses: rinx/setup-k3d@v0.0.3
      with:
        version: v3.4.0
        ingressPort: 80
        agents: 1
    - name: Wait for k3s ready
      run: |
        while true
        do
          kubectl get pod --all-namespaces
          if kubectl wait --for=condition=ready pod --selector=app.kubernetes.io/name=traefik --namespace=kube-system
          then
            break
          else
            echo "k3s not ready"
            sleep 5
          fi
        done
    - name: Setup .NET SDK 5
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'
    - name: Install dependencies
      run: dotnet restore
    - name: Install tool dependencies
      run: dotnet tool restore
    - name: Check formatting
      run: dotnet tool run fantomas --check --recurse src
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    - name: Run SimplePayment mission
      run: dotnet run --project src/App/App.fsproj --configuration Release -- mission SimplePayment --kubeconfig $KUBECONFIG --namespace default --ingress-class traefik --ingress-internal-domain local --ingress-external-host localhost --uneven-sched
    - uses: actions/upload-artifact@v2
      with:
        name: destination
        path: destination/
        retention-days: 30
